import { supabase } from "@/integrations/supabase/client";

const PROJECT_ID = import.meta.env.VITE_SUPABASE_PROJECT_ID;
const FN_URL = `https://${PROJECT_ID}.supabase.co/functions/v1/sheets-read`;

// ─── Vault Sync Loader ────────────────────────────────────────────────────────
// Primary data source: vault-sync.json (auto-generated by post-commit hook)
// Fallback: Sheets API, then demo data

interface VaultSyncData {
  advisor_questions: Array<{ id: string; date_raised: string; question: string; what_i_tried: string; status: string; answer: string; answered_date: string; priority: string }>;
  outreach: Array<{ name: string; org: string; role: string; email: string; type: string; status: string; date: string; priority: string; notes: string }>;
  evidence: Array<{ claim: string; proof: string; location: string; status: string }>;
  decision_log: Array<{ date: string; decision: string; rationale: string; source_question_id: string; status: string }>;
  timeline: Array<{ phase: string; week: string; dates: string; milestone: string; owner: string; status: string; priority: string; layer: string; notes: string }>;
  generated_at: string;
  vault_root: string;
}

let vaultSyncData: VaultSyncData | null = null;

async function loadVaultSync(): Promise<VaultSyncData | null> {
  if (vaultSyncData) return vaultSyncData;

  try {
    // Try to fetch vault-sync.json from the public data directory (served from /data/)
    const res = await fetch('/data/vault-sync.json');
    if (res.ok) {
      vaultSyncData = await res.json();
      return vaultSyncData;
    }
  } catch (e) {
    // Fall through to Sheets/demo fallback if fetch fails
  }

  return null;
}

// GPU Telemetry columns (A–I, 9 cols) — written by Colab collector
// A:timestamp  B:temp_c  C:power_w  D:power_cap_w  E:sm_clock_mhz
// F:mem_clock_mhz  G:util_pct  H:headroom_c  I:rtheta_cwatt
export interface MeasurementRow {
  timestamp: string;
  tempC: number;
  powerW: number;
  powerCapW: number;
  smClockMhz: number;
  memClockMhz: number;
  utilPct: number;
  headroomC: number;
  rthetaCwatt: number;
  // Derived
  alert: string;
}

export interface TimelineRow {
  phase: string; week: string; dates: string; milestone: string; owner: string;
  status: string; priority: string; layer: string; notes: string;
}

async function readRange(range: string): Promise<string[][]> {
  const { data: { session } } = await supabase.auth.getSession();
  const headers: Record<string, string> = {
    apikey: import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY,
  };
  if (session?.access_token) {
    headers.Authorization = `Bearer ${session.access_token}`;
  }
  const res = await fetch(`${FN_URL}?range=${encodeURIComponent(range)}`, { headers });
  if (!res.ok) throw new Error(`sheets-read ${res.status}`);
  const data = await res.json();
  if (data.error === "missing_config") throw new Error("DEMO_MODE");
  if (data.error) throw new Error(data.error?.message ?? String(data.error));
  return data.values ?? [];
}


function deriveAlert(m: Omit<MeasurementRow, "alert">): string {
  if (m.tempC >= 85) return "HOT";
  if (m.rthetaCwatt > 1.8) return "HIGH_RTHETA";
  if (m.headroomC < 15) return "LOW_HEADROOM";
  return "OK";
}

export async function fetchMeasurements(): Promise<MeasurementRow[]> {
  const rows = await readRange("'📡 Measurements'!A4:I2000");
  return rows.filter((r) => r[0] && r[1]).map((r) => {
    const base = {
      timestamp: r[0] ?? "",
      tempC: parseFloat(r[1]) || 0,
      powerW: parseFloat(r[2]) || 0,
      powerCapW: parseFloat(r[3]) || 0,
      smClockMhz: parseFloat(r[4]) || 0,
      memClockMhz: parseFloat(r[5]) || 0,
      utilPct: parseFloat(r[6]) || 0,
      headroomC: parseFloat(r[7]) || 0,
      rthetaCwatt: parseFloat(r[8]) || 0,
    };
    return { ...base, alert: deriveAlert(base) };
  });
}

export async function fetchTimeline(): Promise<TimelineRow[]> {
  // Try vault-sync first
  const vault = await loadVaultSync();
  if (vault?.timeline) {
    return vault.timeline;
  }

  // Fallback to Sheets
  const rows = await readRange("'🗓 Master Timeline'!A4:I200");
  let lastPhase = "";
  return rows.filter((r) => r[3]).map((r) => {
    if (r[0]) lastPhase = r[0];
    return {
      phase: lastPhase, week: r[1] ?? "", dates: r[2] ?? "", milestone: r[3] ?? "",
      owner: r[4] ?? "", status: r[5] ?? "Not Started", priority: r[6] ?? "P2 — Normal",
      layer: r[7] ?? "", notes: r[8] ?? "",
    };
  });
}

// ---------- DEMO DATA ----------

export function generateDemoMeasurements(count = 60): MeasurementRow[] {
  const now = Date.now();
  const THROTTLE_TEMP = 93;

  return Array.from({ length: count }, (_, i) => {
    // Simulate: idle for first 10, ramp up, stabilize under load
    const phase = i < 10 ? "idle" : i < 20 ? "ramp" : "load";
    const tempC = phase === "idle"
      ? 40 + Math.sin(i * 0.8) * 0.5
      : phase === "ramp"
        ? 40 + (i - 10) * 3.4
        : 74 + Math.sin(i * 1.2) * 1.5;
    const powerW = phase === "idle"
      ? 9.5 + Math.random() * 0.3
      : phase === "ramp"
        ? 9.5 + (i - 10) * 6
        : 68 + Math.sin(i * 0.9) * 2;
    const powerCapW = 70;
    const smClockMhz = phase === "idle" ? 300 : phase === "ramp" ? 300 + (i - 10) * 150 : 1590 + Math.random() * 20;
    const memClockMhz = phase === "idle" ? 405 : 5001;
    const utilPct = phase === "idle" ? 0 : phase === "ramp" ? (i - 10) * 10 : 95 + Math.random() * 5;
    const headroomC = +(THROTTLE_TEMP - tempC).toFixed(1);
    const rthetaCwatt = powerW > 1 ? +((tempC - 25) / powerW).toFixed(4) : 0;

    const base = {
      timestamp: new Date(now - (count - i) * 1000).toISOString(),
      tempC: +tempC.toFixed(1),
      powerW: +powerW.toFixed(2),
      powerCapW,
      smClockMhz: Math.round(smClockMhz),
      memClockMhz,
      utilPct: Math.round(utilPct),
      headroomC,
      rthetaCwatt,
    };
    return { ...base, alert: deriveAlert(base) };
  });
}

export function generateDemoTimeline(): TimelineRow[] {
  return [
    // Stage 1 — Colab baseline (complete)
    { phase: "Stage 1 — Colab baseline", week: "W1–W4", dates: "May 2026", milestone: "E001–E004: idle, same-process, cross-process, controlled-variable cooldown trials", owner: "Amogh", status: "Done ✓", priority: "P0 — Critical", layer: "Research", notes: "8,734 rows · 14 trials · Tesla T4" },
    { phase: "", week: "W3", dates: "May 2026", milestone: "F1 confirmed: 2°C ambient → 3.5× recovery time (n=7, CV 1.8%)", owner: "Amogh", status: "Done ✓", priority: "P0 — Critical", layer: "Research", notes: "Controlled-variable study E004 v2" },
    { phase: "", week: "W4", dates: "May 2026", milestone: "Classifier: Naive Bayes 87% → Decision Tree 100% with steady-state filter", owner: "Amogh", status: "Done ✓", priority: "P1 — High", layer: "SW", notes: "Orange Data Mining + sklearn" },
    { phase: "", week: "W4", dates: "May 2026", milestone: "Kundu advisor confirmed · 3 mandates filed (sensitivity, Bayesian, E003/E004 rerun)", owner: "Amogh", status: "Done ✓", priority: "P0 — Critical", layer: "Comms", notes: "2026-06-03 session" },

    // Stage 2 — Agent v0.1.9 (complete)
    { phase: "Stage 2 — Agent v0.1.9", week: "W5", dates: "Jun 2026", milestone: "pip install runtheta · pynvml + Redfish + DCGM telemetry collector", owner: "Amogh", status: "Done ✓", priority: "P0 — Critical", layer: "SW", notes: "v0.1.8" },
    { phase: "", week: "W5", dates: "Jun 2026", milestone: "Fault curve classifier: 6 failure modes from R_θ(P) shape (dust, TIM, fan, blockage, mounting, HBM)", owner: "Amogh", status: "Done ✓", priority: "P0 — Critical", layer: "SW", notes: "v0.1.9 · fault_classifier.py" },
    { phase: "", week: "W5", dates: "Jun 2026", milestone: "Discovery outreach: RunPod, Vast.ai, Lambda Labs — awaiting replies", owner: "Amogh", status: "In Progress", priority: "P0 — Critical", layer: "Comms", notes: "Sent 2026-06-02" },
    { phase: "", week: "W5", dates: "Jun 2026", milestone: "Lupo proposal + Campus IT one-pager ready to send", owner: "Amogh", status: "In Progress", priority: "P0 — Critical", layer: "Comms", notes: "Gated on Lupo meeting" },

    // Stage 3 — AI Factory deployment (in progress)
    { phase: "Stage 3 — AI Factory deployment", week: "W6", dates: "Jun–Jul 2026", milestone: "Lupo meeting · deliver AI Factory proposal · get greenlight", owner: "Amogh", status: "Not Started", priority: "P0 — Critical", layer: "Comms", notes: "Gating milestone for Stage 3" },
    { phase: "", week: "W7", dates: "Jul 2026", milestone: "Canary install on 1 of 4 DGX B200 nodes · BMC-measured ambient", owner: "Amogh", status: "Not Started", priority: "P0 — Critical", layer: "SW", notes: "Needs Lupo greenlight first" },
    { phase: "", week: "W8", dates: "Jul 2026", milestone: "E005: power-cap sweep at 6 levels on DGX B200 · compare to T4 baseline", owner: "Amogh", status: "Not Started", priority: "P1 — High", layer: "Research", notes: "First dedicated-hardware experiment" },
    { phase: "", week: "W8", dates: "Jul 2026", milestone: "TARUC integration angle confirmed with Lupo · ICPE 2027 co-authorship scoped", owner: "Both", status: "Not Started", priority: "P1 — High", layer: "Comms", notes: "" },

    // Stage 4 — Anomaly detector v2 (locked)
    { phase: "Stage 4 — Anomaly detector v2 + sensitivity", week: "W9", dates: "Aug 2026", milestone: "dR_θ/dT_amb sensitivity analysis at each power tier (Kundu mandate)", owner: "Amogh", status: "Not Started", priority: "P0 — Critical", layer: "Research", notes: "Q_sensitivity_analysis" },
    { phase: "", week: "W9", dates: "Aug 2026", milestone: "E003 + E004 rerun on DGX B200 · n ≥ 10 trials · steady-state window + Bayesian", owner: "Amogh", status: "Not Started", priority: "P0 — Critical", layer: "Research", notes: "Kundu mandate 2026-06-03" },
    { phase: "", week: "W10", dates: "Aug 2026", milestone: "Bayesian classifier refit on DGX data · model equation extracted · compare vs RF", owner: "Amogh", status: "Not Started", priority: "P1 — High", layer: "SW", notes: "" },
    { phase: "", week: "W10", dates: "Aug–Sep 2026", milestone: "Lead-time prediction (E-LT testbed with Sam · fault induction · fall 2026)", owner: "Sam", status: "Not Started", priority: "P1 — High", layer: "EE", notes: "Sam returns fall 2026" },

    // Stage 5 — Publication (locked)
    { phase: "Stage 5 — Multi-GPU validation + publication", week: "W11", dates: "Sep–Dec 2026", milestone: "A100 / H100 / RTX generalization experiments", owner: "Amogh", status: "Not Started", priority: "P1 — High", layer: "Research", notes: "" },
    { phase: "", week: "W12", dates: "Oct 2026", milestone: "EE 4400 project: formal course credit for Stage 2–4 experiments", owner: "Amogh", status: "Not Started", priority: "P1 — High", layer: "Research", notes: "Fall 2026 semester" },
    { phase: "", week: "W13", dates: "Nov 2026", milestone: "Conference paper draft · two-dim F1 finding · sensitivity confidence bands", owner: "Both", status: "Not Started", priority: "P0 — Critical", layer: "Research", notes: "ICPE 2027 target" },
    { phase: "", week: "W14", dates: "Sep 2026", milestone: "YC W27 application · submit by September deadline", owner: "Amogh", status: "Not Started", priority: "P0 — Critical", layer: "Comms", notes: "Cal Poly student window" },
  ];
}

export function isDemoModeError(err: unknown): boolean {
  return err instanceof Error && err.message === "DEMO_MODE";
}

// ---------- OUTREACH ----------
export interface OutreachRow {
  name: string; org: string; role: string; email: string;
  type: string; status: string; date: string; priority: string; notes: string;
}

export async function fetchOutreach(): Promise<OutreachRow[]> {
  // Try vault-sync first
  const vault = await loadVaultSync();
  if (vault?.outreach) {
    return vault.outreach;
  }

  // Fallback to Sheets
  const rows = await readRange("'📬 Outreach'!A4:I200");
  return rows.filter((r) => r[0]).map((r) => ({
    name: r[0] ?? "", org: r[1] ?? "", role: r[2] ?? "", email: r[3] ?? "",
    type: r[4] ?? "", status: r[5] ?? "Not Contacted",
    date: r[6] ?? "", priority: r[7] ?? "P2 — Normal", notes: r[8] ?? "",
  }));
}

export function generateDemoOutreach(): OutreachRow[] {
  return [
    { name: "Prof. Souvik Kundu", org: "Cal Poly EE", role: "Assistant Professor", email: "sokundu@calpoly.edu", type: "Advisor", status: "Active", date: "6/3/2026", priority: "P0 — Critical", notes: "Last session 2026-06-03: 3 mandates (sensitivity analysis, Bayesian, E003/E004 rerun). Conference publication confirmed as primary output." },
    { name: "Prof. Christopher Lupo", org: "Cal Poly Noyce School", role: "Founding Director, CS&SE Chair", email: "clupo@calpoly.edu", type: "Deployment Sponsor", status: "Proposal Ready", date: "6/5/2026", priority: "P0 — Critical", notes: "20-min meeting request. Pitch: extend Sandia HPC Resilience Testbed (2015) to thermal-power layer on B200. ICPE 2027 + TARUC integration angle." },
    { name: "Prof. Helen Yu", org: "Cal Poly EE", role: "Professor", email: "xhyu@calpoly.edu", type: "Advisor", status: "First meeting pending", date: "5/13/2026", priority: "P1 — High", notes: "Signal processing angle for adaptive control." },
    { name: "Ryan Xu", org: "Redbrick (student VC)", role: "Partner", email: "—", type: "Pitch Comp + Mentorship", status: "First meeting done", date: "6/2/2026", priority: "P1 — High", notes: "Not a funder — pitch competition + connections to local VCs. Reconnect for follow-up." },
    { name: "RunPod (infra team)", org: "RunPod", role: "Infrastructure", email: "X / Discord #infrastructure", type: "Neocloud (discovery)", status: "Awaiting reply", date: "6/2/2026", priority: "P0 — Critical", notes: "Sent X/Discord message 2026-06-02. Ask: how do you separate hot-because-busy from hot-because-failing?" },
    { name: "Vast.ai (community)", org: "Vast.ai", role: "Ops / Community", email: "support@vast.ai", type: "Neocloud (discovery)", status: "Awaiting reply", date: "6/2/2026", priority: "P0 — Critical", notes: "Sent email 2026-06-02. Marketplace reliability angle — bad-node detection." },
    { name: "Lambda Labs (eng)", org: "Lambda Labs", role: "Infra Engineer", email: "X DM / replies", type: "Neocloud (discovery)", status: "Awaiting reply", date: "6/2/2026", priority: "P0 — Critical", notes: "Sent X DM 2026-06-02. Already a Lambda customer; peer framing." },
    { name: "Cal Poly Campus IT", org: "Cal Poly", role: "Cluster Ops", email: "TBD", type: "Deployment", status: "Blocked on Lupo", date: "", priority: "P1 — High", notes: "Campus IT one-pager ready. Routes through Lupo first — sequenced after AI Factory greenlight." },
  ];
}

// ---------- EVIDENCE BOARD ----------
export interface EvidenceRow {
  claim: string; proof: string; location: string; status: string;
}

export async function fetchEvidence(): Promise<EvidenceRow[]> {
  // Try vault-sync first
  const vault = await loadVaultSync();
  if (vault?.evidence) {
    return vault.evidence;
  }

  // Fallback to Sheets
  const rows = await readRange("'🏆 Evidence Board'!A4:D50");
  return rows.filter((r) => r[0]).map((r) => ({
    claim: r[0] ?? "", proof: r[1] ?? "", location: r[2] ?? "",
    status: r[3] ?? "No proof yet",
  }));
}

export function generateDemoEvidence(): EvidenceRow[] {
  return [
    { claim: "Controlled-variable F1: 2°C ambient → 3.5× recovery time", proof: "E004 v2 (2026-06-04): 7-trial controlled study, within-condition CV 1.8%. 1800s pre-trial wait → 3-5s recovery vs 10-37s without.", location: "vault/wiki/experiments/E004.md + vault/raw/code/E004v2_COLAB_FINAL.py", status: "Evidence collected" },
    { claim: "Utilization is a broken thermal state signal", proof: "E002: GPU held 74°C / 31W for 10 min at 0% util after same-process workload exit (zombie state)", location: "vault/wiki/experiments/E002.md", status: "Evidence collected" },
    { claim: "Child-exit recovery is consistent (P-state → P8 in 5-6s)", proof: "E004: all 7 trials recovered P-state in 5.1-6.1s regardless of starting temperature", location: "vault/wiki/experiments/E004.md", status: "Evidence collected" },
    { claim: "Rθ sensitivity quantified: dRθ/dT_amb = -1/P", proof: "F2: idle 7.1% / °C, load 2.0% / °C. Idle is 3.5× more sensitive than load. Kundu mandate 2026-06-03: present R_θ with confidence bands.", location: "vault/wiki/findings/F2.md", status: "Evidence collected" },
    { claim: "Classifier reaches 100% with steady-state filter", proof: "Naive Bayes raw 87.0%, with 15s steady-state filter 99.9%. Random Forest with filter 100%. Steady-state filter is the highest-leverage preprocessing step.", location: "vault/wiki/synthesis/classifier_comparison_orange.md", status: "Evidence collected" },
    { claim: "Fault curve classifier shipped — 6 failure modes from R_θ(P) shape", proof: "v0.1.9 (2026-06-05): dust, TIM, fan, blockage, mounting, HBM. Causal diagnosis with remediation, not just anomaly flags.", location: "thermalos-agent/thermalos/agent/fault_classifier.py + vault/wiki/concepts/rtheta_fault_taxonomy.md", status: "Evidence collected" },
    { claim: "Cal Poly AI Factory deployment proposal ready", proof: "Lupo one-pager + Campus IT brief written, PDFs generated. TARUC integration angle → ICPE 2027 co-authorship.", location: "vault/raw/strategy/pdfs/thermalos_lupo_proposal.pdf", status: "Awaiting Lupo meeting" },
    { claim: "Neocloud discovery outreach in flight", proof: "RunPod, Vast.ai, Lambda Labs — outreach sent 2026-06-02 via X/email/Discord. Discovery (not pitch).", location: "vault/wiki/sources/outreach_messages_2026_06_02.md", status: "Awaiting replies" },
    { claim: "Kundu informal advising active; EE 4400 fall confirmed", proof: "2026-06-03 session: 3 mandates filed (sensitivity, Bayesian, E003/E004 rerun). AI Factory access via informal advising.", location: "vault/wiki/sources/kundu_session_2026_06_03.md", status: "Evidence collected" },
    { claim: "Power-cap sweep on dedicated hardware", proof: "E005 planned — 6 power levels on DGX B200, BMC-measured ambient", location: "vault/wiki/experiments/E005.md (planned)", status: "No proof yet" },
    { claim: "Lead-time validation (E-LT testbed)", proof: "Controlled induction of 5 failure modes on Sam's heater-block rig, fall 2026", location: "vault/wiki/experiments/E-LT.md (Fall 2026)", status: "No proof yet" },
    { claim: "Cal Poly AI Factory live deployment", proof: "Canary install on 1 of 4 DGX B200 nodes after Lupo greenlight", location: "vault/wiki/synthesis/cal_poly_deployment_strategy.md", status: "Pending Lupo response" },
  ];
}

// ---------- TODAY PLAN ----------
export interface TodayRow {
  priority: string; phase: string; milestone: string;
  owner: string; track: string; notes: string;
}

export async function fetchTodayPlan(): Promise<TodayRow[]> {
  const rows = await readRange("'📋 Today Plan'!A4:F100");
  return rows.filter((r) => r[2]).map((r) => ({
    priority: r[0] ?? "", phase: r[1] ?? "", milestone: r[2] ?? "",
    owner: r[3] ?? "", track: r[4] ?? "", notes: r[5] ?? "",
  }));
}

// ---------- ADVISOR QUESTIONS ----------

export interface AdvisorQuestion {
  id: string;
  date_raised: string;
  question: string;
  what_i_tried: string;
  status: "open" | "in_discussion" | "answered";
  answer: string;
  answered_date: string;
  priority: "high" | "normal" | "low";
}

export async function fetchAdvisorQuestions(): Promise<AdvisorQuestion[]> {
  // Try vault-sync first
  const vault = await loadVaultSync();
  if (vault?.advisor_questions) {
    return vault.advisor_questions.map(r => ({
      id: r.id,
      date_raised: r.date_raised,
      question: r.question,
      what_i_tried: r.what_i_tried,
      status: r.status as AdvisorQuestion["status"],
      answer: r.answer,
      answered_date: r.answered_date,
      priority: r.priority as AdvisorQuestion["priority"],
    }));
  }

  // Fallback to Sheets
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data, error } = await (supabase as any)
    .from("advisor_questions")
    .select("*")
    .order("date_raised", { ascending: false });
  if (error || !data) throw new Error("DEMO_MODE");
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return data.map((r: any) => ({
    id: r.id,
    date_raised: r.date_raised ? (r.date_raised as string).slice(0, 10) : "",
    question: r.question,
    what_i_tried: r.what_i_tried ?? "",
    status: r.status as AdvisorQuestion["status"],
    answer: r.answer ?? "",
    answered_date: r.answered_at ? (r.answered_at as string).slice(0, 10) : "",
    priority: r.priority as AdvisorQuestion["priority"],
  }));
}

export async function updateQuestionAnswer(
  id: string,
  answer: string,
  status: AdvisorQuestion["status"],
  answeredBy: string,
): Promise<void> {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { error } = await (supabase as any)
    .from("advisor_questions")
    .update({ answer, status, answered_by: answeredBy, answered_at: new Date().toISOString() })
    .eq("id", id);
  if (error) throw error;
}

export function generateDemoAdvisorQuestions(): AdvisorQuestion[] {
  return [
    {
      id: "q1",
      date_raised: "2026-05-20",
      question: "How do we handle T_reference uncertainty at low power loads? At 9.5W idle, a 5C ambient error causes a 35% R_theta swing.",
      what_i_tried: "Ran F002 sensitivity analysis assuming T_ref = 25C from literature. Found 35.3% swing at idle vs 10.2% at load. The metric is most sensitive exactly when power is lowest -- and that is when anomaly detection matters most.",
      status: "open",
      answer: "",
      answered_date: "",
      priority: "high",
    },
    {
      id: "q2",
      date_raised: "2026-05-20",
      question: "Rolling average vs median filter vs steady-state window for R_theta computation -- which method is most valid?",
      what_i_tried: "Implemented 5s rolling average and 5s median filter, compared against raw power. R_theta std improved by 3.5% max (rolling avg), negligible with median. Variance source is T_reference uncertainty, not power noise (F003 null result).",
      status: "answered",
      answer: "Use steady-state window. The null result confirms filtering does not address the root cause. Do not add complexity that does not reduce the dominant error source.",
      answered_date: "2026-05-27",
      priority: "normal",
    },
    {
      id: "q3",
      date_raised: "2026-05-20",
      question: "Is the rule-based state classifier statistically valid, or should it be probabilistic? Current thresholds misclassify 47-98% of transitional phases.",
      what_i_tried: "Implemented thresholds: util < 5%, power < 15W, temp < 55C. Works on stable endpoints but fails transitional phases (F004). Reviewed Orange Data Mining -- Naive Bayes and Random Forest both viable. Goal is a model equation, not a black box.",
      status: "answered",
      answer: "Apply other classification techniques -- Random Forest, RL, or Bayesian. Best one I think is Bayesian. Try Python packages or Orange Data Mining for best visualization -- it will give you classification rules you can compare and find a model equation. Compare classifiers and find which fits best.",
      answered_date: "2026-06-03",
      priority: "high",
    },
    {
      id: "q4",
      date_raised: "2026-05-22",
      question: "Is the ~447MB NVML memory reported with no active processes a state variable or a driver artifact?",
      what_i_tried: "Observed consistently across E001-E004 in both nvidia-smi and pyNVML. Appears at driver load, persists through process exit. No named processes attached. Not documented in NVIDIA driver release notes.",
      status: "open",
      answer: "",
      answered_date: "",
      priority: "normal",
    },
    {
      id: "q5",
      date_raised: "2026-05-20",
      question: "t-test vs Mann-Whitney U for small-sample recovery comparison -- given n=3 trials, which is appropriate?",
      what_i_tried: "n=3 cross-trial CV is low (1.68% load, 0.64% recovery). t-test requires normality at n=3 which is hard to justify. Mann-Whitney U is non-parametric but loses power at small n. Standard recommendation is n >= 10 before reporting p-values.",
      status: "answered",
      answer: "Hold t-test and p-value comparisons until we have a lot more data, or when we are presenting findings. Sample sizes need to be larger before formal statistical tests are publication-grade.",
      answered_date: "2026-06-03",
      priority: "normal",
    },
    {
      id: "q6",
      date_raised: "2026-06-03",
      question: "How should we treat T_reference uncertainty in publication? Currently presenting R_theta as a point estimate at T_amb = 25C is not defensible.",
      what_i_tried: "Stage 1 used a fixed T_ref = 25C from literature. F002 sensitivity analysis showed 35% R_theta swing at idle with +/-5C ambient error. Reviewers will ask 'what was ambient?' and the assumed-constant answer is not enough at conference level.",
      status: "answered",
      answer: "Do the sensitivity analysis -- change in response with respect to temperature. We are saying a static ambient temperature, but per degree. From a research perspective, sensitivity analysis in factors you do not know is very important. Either claim it only works at higher power, or do dR_theta/dT_amb at each power level.",
      answered_date: "2026-06-03",
      priority: "high",
    },
    {
      id: "q7",
      date_raised: "2026-06-03",
      question: "Should we rerun E003 and E004 on Stage 2 hardware before publication, or trust Stage 1 data?",
      what_i_tried: "E004 v2 (controlled-variable) already completed 2026-06-04 with 7 trials, CV 1.8% within thermal regime. E003 has same-process zombie state finding (F6) but only n=3.",
      status: "answered",
      answer: "Let us redo E003 and E004. Both need fresh runs with the steady-state window and Bayesian classifier in place. E004 rerun script is ready; plan E003 rerun next.",
      answered_date: "2026-06-03",
      priority: "high",
    },
  ];
}

// ---------- DECISION LOG ----------

export interface DecisionLogRow {
  date: string;
  decision: string;
  rationale: string;
  source_question_id: string;
  status: "active" | "superseded";
}

export async function fetchDecisionLog(): Promise<DecisionLogRow[]> {
  // Try vault-sync first
  const vault = await loadVaultSync();
  if (vault?.decision_log) {
    return vault.decision_log.map(r => ({
      date: r.date,
      decision: r.decision,
      rationale: r.rationale,
      source_question_id: r.source_question_id,
      status: r.status as DecisionLogRow["status"],
    }));
  }

  // Fallback to Sheets
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data, error } = await (supabase as any)
    .from("decision_log")
    .select("*")
    .order("created_at", { ascending: false });
  if (error || !data) throw new Error("DEMO_MODE");
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return data.map((r: any) => ({
    date: r.created_at ? (r.created_at as string).slice(0, 10) : "",
    decision: r.decision,
    rationale: r.rationale ?? "",
    source_question_id: r.source_question_id ?? "",
    status: r.status as DecisionLogRow["status"],
  }));
}

export function generateDemoDecisionLog(): DecisionLogRow[] {
  return [
    {
      date: "2026-06-03",
      decision: "Compute dR_theta/dT_amb sensitivity at every power tier; present R_theta with confidence bands, not as a point estimate",
      rationale: "Kundu (2026-06-03): sensitivity analysis in factors we do not know is a research priority. Required for publication.",
      source_question_id: "q6",
      status: "active",
    },
    {
      date: "2026-06-03",
      decision: "Apply Bayesian classifier and compare to Random Forest using Orange Data Mining; extract model equation",
      rationale: "Kundu (2026-06-03): Bayesian is the best fit, but compare against RF in Orange to find which rules emerge. The goal is a model equation, not a black box. Already implemented v0.1.9; supersedes 2026-05-27 in-discussion entry.",
      source_question_id: "q3",
      status: "active",
    },
    {
      date: "2026-06-03",
      decision: "Rerun E003 and E004 with steady-state filter and classifier in place",
      rationale: "Kundu (2026-06-03): redo both experiments. E004 rerun script ready; E003 rerun protocol to plan next.",
      source_question_id: "q7",
      status: "active",
    },
    {
      date: "2026-06-05",
      decision: "Ship fault curve classifier v0.1.9 — 6 failure modes from R_theta(P) shape",
      rationale: "Dust, TIM, fan, blockage, mounting, HBM thermal — each has a distinct R_theta curve signature. Classifier ships causal diagnosis with remediation, not just anomaly flags. Validation path: E-LT controlled induction.",
      source_question_id: "",
      status: "active",
    },
    {
      date: "2026-05-27",
      decision: "Use steady-state window for R_theta computation",
      rationale: "Rolling avg and median filter both showed negligible improvement (3.5% max). Dominant error source is T_reference uncertainty, not power noise. Simpler is better.",
      source_question_id: "q2",
      status: "active",
    },
    {
      date: "2026-05-27",
      decision: "Pursue Bayesian classification over hardcoded thresholds",
      rationale: "Rule-based classifier fails 47-98% of transitional phases. Bayesian approach via Orange Data Mining allows probabilistic state assignment and produces a model equation rather than a black box.",
      source_question_id: "q3",
      status: "superseded",
    },
    {
      date: "2026-05-27",
      decision: "Redo E003 and E004 with 10+ trials on Stage 2 hardware",
      rationale: "n=3 is insufficient for statistical testing. Need n >= 10 before reporting confidence intervals. Repeat on dedicated hardware where ambient is controlled.",
      source_question_id: "q5",
      status: "superseded",
    },
    {
      date: "2026-05-27",
      decision: "Hold formal t-tests and p-values until sample is larger",
      rationale: "n=3 descriptive stats are promising but formal tests are unreliable at this sample size. Report CV and descriptive stats only until Stage 2 replications are complete.",
      source_question_id: "q5",
      status: "active",
    },
    {
      date: "2026-05-27",
      decision: "Target a conference publication as the end goal",
      rationale: "Kundu confirmed this is the appropriate end goal. The research should culminate in a publication. YC application uses the results, but the research is the primary output. Venue TBD -- confirm with Kundu.",
      source_question_id: "",
      status: "active",
    },
  ];
}

// ---------- ADVISOR ASKS ----------

export interface AdvisorAsk {
  id: string;
  ask: string;
  status: "open" | "resolved";
}

export async function fetchAdvisorAsks(): Promise<AdvisorAsk[]> {
  // Fallback to Sheets (advisor_asks not yet in vault-sync, but ready to integrate)
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data, error } = await (supabase as any)
    .from("advisor_asks")
    .select("*")
    .order("ask");
  if (error || !data) throw new Error("DEMO_MODE");
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return data.map((r: any) => ({
    id: r.id,
    ask: r.ask,
    status: r.status as AdvisorAsk["status"],
  }));
}

export function generateDemoAdvisorAsks(): AdvisorAsk[] {
  return [
    { id: "a1", ask: "Confirm conference target venue and submission deadline (ICPE 2027 is the working target — please verify)", status: "open" },
    { id: "a2", ask: "Intro Amogh to Prof. Lupo (Noyce founding director) to deliver the AI Factory deployment proposal", status: "open" },
    { id: "a3", ask: "Cal Poly email confirmation for Supabase advisor-questions sign-in (currently sokundu@calpoly.edu)", status: "open" },
    { id: "a4", ask: "Confirm whether informal summer advising suffices to support an AI Factory cluster access request to the Noyce School", status: "resolved" },
  ];
}

export function generateDemoTodayPlan(): TodayRow[] {
  return [
    { priority: "P0 — Critical", phase: "Stage 3 — AI Factory", milestone: "Draft and send Lupo email (warm via Kundu CC, or cold) — 20-min meeting request", owner: "Amogh", track: "Comms", notes: "Proposal PDF + Campus IT one-pager ready. Deadline: Fri Jun 12" },
    { priority: "P0 — Critical", phase: "Stage 3 — AI Factory", milestone: "Follow up with Kundu: brief him on Lupo outreach strategy, get blessing or intro", owner: "Amogh", track: "Comms", notes: "Email Monday. Keep short — one paragraph, one ask" },
    { priority: "P0 — Critical", phase: "Discovery", milestone: "Monitor RunPod / Vast.ai / Lambda replies — respond within 24h if they reply", owner: "Amogh", track: "Comms", notes: "Outreach sent 2026-06-02. First reply unlocks first discovery call." },
    { priority: "P1 — High", phase: "Stage 4 — Research", milestone: "Run dR_θ/dT_amb sensitivity analysis (Kundu mandate) on Stage 1 CSV data", owner: "Amogh", track: "Research", notes: "Vary T_ref 20–30°C, compute R_theta at each power tier, plot sensitivity curve" },
    { priority: "P1 — High", phase: "Stage 4 — Research", milestone: "Plan E003 rerun protocol — n ≥ 10 trials, steady-state window, Bayesian classifier", owner: "Amogh", track: "Research", notes: "E004 rerun script already ready; E003 needs same treatment" },
    { priority: "P1 — High", phase: "Product", milestone: "Implement theta calibrate — per-GPU baseline fingerprint stored to ~/.theta/baselines/", owner: "Amogh", track: "Software", notes: "Prerequisite for any live operator install. Moat dimension 2." },
    { priority: "P2 — Normal", phase: "Product", milestone: "Add Grafana annotation hook to agent — emit R_theta anomaly events as Grafana annotations", owner: "Amogh", track: "Software", notes: "Low effort, high operator value. Operators already have Grafana." },
  ];
}

// ---------- COMMAND CENTER (written by sync-to-sheets skill) ----------

export interface CommandCenterAction {
  action: string;
  why: string;
  how_steps: string[];
  effort: string;
  source: string;
}

export interface CommandCenterOnDeck {
  title: string;
  why: string;
}

export interface CommandCenterBlocker {
  what: string;
  type: string;
  how_to_unblock: string;
  owner: string;
  days_open: number;
}

export interface CommandCenterEscalation {
  question: string;
  route_to: string;
  why: string;
  draft_ask: string;
}

export interface CommandCenter {
  the_one_thing: CommandCenterAction;
  on_deck: CommandCenterOnDeck[];
  blockers: CommandCenterBlocker[];
  escalations: CommandCenterEscalation[];
}

function parseJSON<T>(s: string, fallback: T): T {
  try { return JSON.parse(s) as T; } catch { return fallback; }
}

export async function fetchCommandCenter(): Promise<CommandCenter> {
  const rows = await readRange("'Command Center'!A:B");
  const map: Record<string, string> = {};
  rows.forEach((r) => { if (r[0]) map[r[0]] = r[1] ?? ""; });
  return {
    the_one_thing: parseJSON(map["the_one_thing"] ?? "", generateDemoCommandCenter().the_one_thing),
    on_deck:       parseJSON(map["on_deck"]       ?? "[]", []),
    blockers:      parseJSON(map["blockers"]      ?? "[]", []),
    escalations:   parseJSON(map["escalations"]   ?? "[]", []),
  };
}

export function generateDemoCommandCenter(): CommandCenter {
  return {
    the_one_thing: {
      action: "Get one real operator to install ThermalOS and react to what it shows",
      why: "Outreach is in flight (RunPod/Vast/Lambda sent 2026-06-02). The next unlock is a live install — not a strategy doc, not a deck. One install with a reaction beats ten conversations. This is the difference between a GitHub repo and a company.",
      how_steps: [
        "Monitor replies from RunPod, Vast.ai, Lambda Labs",
        "When a reply comes: offer to join their Slack/Discord and walk through install live",
        "During install: ask 'does this match what you see in your Grafana?' and 'what would make this actionable?'",
        "Collect: what did it detect, was it useful, what workflow should it integrate with",
        "File notes: ingest meeting:[date]-[org]-discovery",
        "Parallel track: Lupo AI Factory install — canary on 1 DGX B200 node",
      ],
      effort: "~3 hours per install including async follow-up",
      source: "wiki/synthesis/moat_analysis_2026_06_05.md",
    },
    on_deck: [
      { title: "Send Lupo email by June 12", why: "AI Factory install is a live production install — counts as customer evidence even if Cal Poly. Lupo is the gating decision-maker." },
      { title: "Implement theta calibrate", why: "Per-GPU baseline fingerprint is moat dimension 2. Prerequisite before any operator install — current T4 thresholds will misfire on A100/H100." },
      { title: "Sensitivity analysis: dR_θ/dT_amb at each power tier", why: "Kundu mandate. Required for publication. Can compute from Stage 1 CSV now — no new hardware needed." },
    ],
    blockers: [
      { what: "No live operator install yet — discovery outreach awaiting replies", type: "external_dependency", how_to_unblock: "Replies from RunPod/Vast/Lambda. Follow up if no reply in 5 business days (Jun 9). Parallel track: Lupo AI Factory.", owner: "Amogh", days_open: 3 },
      { what: "Calibration mode not implemented — T4 thresholds wrong on A100/H100/B200", type: "code_gap", how_to_unblock: "Implement theta calibrate command. Estimated: 1 day. Moat prerequisite.", owner: "Amogh", days_open: 0 },
      { what: "Sam returns to campus — E-LT lead-time testbed blocked until fall 2026", type: "waiting_on_sam", how_to_unblock: "Continue software-only work. Sam picks up E-LT + TIM characterization in fall.", owner: "Sam", days_open: 0 },
    ],
    escalations: [
      { question: "Does CalPoly AI Factory install create a university IP claim on ThermalOS?", route_to: "Kundu", why: "YC will do IP due diligence. Need written confirmation before the canary install.", draft_ask: "Hi Prof. Kundu,\n\nBefore I proceed with the AI Factory canary install, I want to do a quick IP check: does running ThermalOS on Cal Poly infrastructure under your informal advising create any university IP claim on the software? The code was written entirely on personal hardware (Colab T4), so my read is we're clean — but I want to confirm before we plug in.\n\nHappy to discuss at our next meeting or over email.\n\nThanks,\nAmogh" },
      { question: "What is the ICPE 2027 submission deadline and required paper format?", route_to: "Kundu", why: "Publication timeline determines when E-LT experiments must complete. Need the deadline to reverse-plan the fall semester.", draft_ask: "Hi Prof. Kundu,\n\nTo plan the fall experiment schedule: what is the ICPE 2027 submission deadline and paper format (page limit, IEEE style)? I want to make sure E003/E004 reruns and the lead-time validation are done with enough time to write and revise.\n\nThanks,\nAmogh" },
    ],
  };
}

// ---------- WIKI SUMMARY (written by sync-to-sheets skill) ----------

export interface WikiSummary {
  sync_timestamp: string;
  overview_stage: string;
  open_questions_count: string;
  open_questions_list: string;
  experiments_complete: string;
  experiments_planned: string;
  findings_current: string;
  next_action: string;
  conflicts_found: string;
  conflicts_detail: string;
  vault_last_updated: string;
}

export async function fetchWikiSummary(): Promise<WikiSummary> {
  const rows = await readRange("'Wiki Summary'!A:B");
  const map: Record<string, string> = {};
  rows.forEach((r) => { if (r[0]) map[r[0]] = r[1] ?? ""; });
  return {
    sync_timestamp: map["sync_timestamp"] ?? "",
    overview_stage: map["overview_stage"] ?? "",
    open_questions_count: map["open_questions_count"] ?? "",
    open_questions_list: map["open_questions_list"] ?? "",
    experiments_complete: map["experiments_complete"] ?? "",
    experiments_planned: map["experiments_planned"] ?? "",
    findings_current: map["findings_current"] ?? "",
    next_action: map["next_action"] ?? "",
    conflicts_found: map["conflicts_found"] ?? "",
    conflicts_detail: map["conflicts_detail"] ?? "",
    vault_last_updated: map["vault_last_updated"] ?? "",
  };
}

export function generateDemoWikiSummary(): WikiSummary {
  return {
    sync_timestamp: new Date().toISOString(),
    overview_stage: "Stage 1 complete (Colab T4, 8,734 rows, E001–E004 v2). Agent v0.1.9 live on PyPI. Stage 3 (AI Factory) in progress — gated on Lupo meeting.",
    open_questions_count: "13",
    open_questions_list: "Q_lead_time; Q_conference_venue; Q_cross_vendor_calibration; Q_workflow_integration; Q_per_gpu_baseline; Q_university_ip_risk; Q_sensitivity_analysis; Q_ambient_measurement; Q_AI_Factory_access; Q_discovery_progress; Q_slurm_integration; Q_Kundu_email; Q_memory_store",
    experiments_complete: "E001, E002, E003, E004 (v1 + v2 controlled-variable)",
    experiments_planned: "E005, E006, E007, E008 (Stage 2, DGX B200), E-LT (Fall 2026, Sam's testbed)",
    findings_current: "6",
    next_action: "Get first live operator install. Send Lupo email by Jun 12. Implement theta calibrate (per-GPU baseline). Run sensitivity analysis on Stage 1 data.",
    conflicts_found: "1",
    conflicts_detail: "campus_it_one_pager references v0.1.8; agent is now v0.1.9. Update before sending to Campus IT.",
    vault_last_updated: "2026-06-05",
  };
}

// ---------- ROADMAP STAGES ----------

export interface RoadmapStage {
  id: number;
  title: string;
  status: "complete" | "in_progress" | "locked";
  subtitle: string;
  progress: number;
}

export async function fetchRoadmapStages(): Promise<RoadmapStage[]> {
  const rows = await readRange("'🗓 Master Timeline'!A4:I200");

  // Group by phase name, infer status and progress from milestones
  const phaseMap = new Map<string, { items: string[]; doneCount: number }>();

  rows.forEach((r) => {
    const phase = r[0]?.trim();
    const milestone = r[3]?.trim();
    const status = r[5]?.trim()?.toLowerCase() ?? "";

    if (!phase || !milestone) return;

    if (!phaseMap.has(phase)) {
      phaseMap.set(phase, { items: [], doneCount: 0 });
    }

    const p = phaseMap.get(phase)!;
    p.items.push(milestone);
    if (status.includes("done")) p.doneCount++;
  });

  // Convert to RoadmapStage ordered by appearance
  const seenPhases = new Set<string>();
  const stages: RoadmapStage[] = [];

  rows.forEach((r) => {
    const phase = r[0]?.trim();
    if (!phase || seenPhases.has(phase)) return;
    seenPhases.add(phase);

    const data = phaseMap.get(phase)!;
    const progress = data.items.length > 0 ? Math.round((data.doneCount / data.items.length) * 100) : 0;
    const doneCount = data.doneCount;
    const totalCount = data.items.length;
    let status: "complete" | "in_progress" | "locked" = "locked";
    if (doneCount === totalCount) status = "complete";
    else if (doneCount > 0) status = "in_progress";

    stages.push({
      id: stages.length + 1,
      title: phase.replace(/phase \d+ — /i, "").trim(),
      status,
      subtitle: doneCount === totalCount ? `${totalCount} milestones` : `${doneCount}/${totalCount} milestones`,
      progress,
    });
  });

  return stages;
}

export function generateDemoRoadmapStages(): RoadmapStage[] {
  return [
    { id: 1, title: "Colab baseline", status: "complete", subtitle: "Tesla T4 · 2,280+ rows · E001–E003 complete", progress: 100 },
    { id: 2, title: "Dedicated GPU hardware", status: "in_progress", subtitle: "Physical machine · power-cap sweep · E005–E008", progress: 10 },
    { id: 3, title: "Anomaly detector v1", status: "locked", subtitle: "Statistical detector on clean baseline", progress: 0 },
    { id: 4, title: "Multi-GPU validation", status: "locked", subtitle: "A100 / H100 / RTX — generalization", progress: 0 },
  ];
}
